intent_response_dict = {
    "greet":["hello how can i help you!!!"],
    "goodbye":["Bye","It was nice talking to you","See you","ttyl"],
    "faq":["The FAQ page is the primary way to help people visiting your website to get the solution of their problems or doubts, which may visitor, may be face anytime. Frequently asked question page (FAQ pages) help your business briefly and appropriately respond to the needs of your customer."],
    "greetings":["Hey! Very Good Morning. Have a nice day!!"],
    "thanks":["Thanks!!!"],
    "information":["We are providing mainly these types of services right now. \n 1)Walkthrough \n 2)Feedback \n 3)Help Editor \n 4)FAQ"],
    "contact":["For more information you can contact our marketing team."],
    "feedback":["Feedback module  will provide the functionality of taking feedbacks from user as well as it will also be going to reply the feedback of user. It will also categories feedback given by user according to the type like complain, appreciate, review, suggestion and so on so which will be going to helpful to other user next time"],
    "helphelper":["It is a Web base service which will be helpful for any web-application. This service will be helpful and easy to use for users. This service is user-friendly so that the site owner can make changes regarding the web application."],
    "walkthrough":["This module will used to guide the user about the website. This feature will be useful for the new users if some users are visiting our website for the first time. Walkthrough is mainly a module which will show a message about the particular part. First let’s divide it into two parts: Owner-side and User-side."],
    "helpeditor":["The main purpose of this service is to provide help. This service is SAAS so anyone can buy our service and can use for their website. Users need to register themselves for one time for the using the service."],
    "add_faq":["First of all you have to register your self in our service and then subscribe the faq package after that you are able to use it."],
    "add_helpeditor":["First of all you have to register your self in our service and then subscribe the helpeditor package after that you are able to use it."],
    "add_feedback":["First of all you have to register your self in our service and then subscribe the feedback package after that you are able to use it."],
    "add_walkthrough":["First of all you have to register your self in our service and then subscribe the walkthrough package after that you are able to use it."],
    "use_helphelper":["This system providing help as a helper module. It is a Web base service which will be helpful for any web-application. This service will be helpful and easy to use for users. This service is user-friendly so that the site owner can make changes regarding the web application which he/she owns. By using this service users can save their time to develop their web applications."],
    "subscription":["There are two types of plans 1) Monthly and 2) Year. 1)Monthly : 1)Feedback Module : -> 42$ , 2)Walkthrough Module : -> 45$, 3) FAQ Module : -> 24$, 4) Helpeditor : -> 30$. 2) Yearly : 1)Feedback Module : -> 420$ , 2)Walkthrough Module : -> 450$, 3) FAQ Module : -> 240$, 4) Helpeditor : -> 300$."],
    "subscription_subscribe":["There are two types of Payment through you subscribe our packages. 1)Internation : Using Stripe and 2)National: Using Paytm, Bank."],
    "subscription_down_charge":["Not Display Now"],
    "subscription_up":["There are some benefits to you if you want to upgrade your current Plans."],
    "feedback_feature":["We provide one Feedback module to our Customers. End user can give feedback to the product owner that how they are satisfied with the product or not.They can ask doubts or question regarding product. And product owner can read this as well as reply to them.They also attach local files and images."],
    "faq_feature":["We provide one FAQ module to our Customers. This FAQ module has some basic and some advanced functionality. By using this module any Product User of the website of Product Owner which subscribe this service, can ask the question, he can search the frequent solution for his problem and also he can suggest modifications to the questions or ask the Product Owner. In addition, if Product Owner finds that any question is very much helpful for other users then he can directly add that Question-answer in his FAQ list so that other users can see that and it may helpful for his problems he found"],
    "walkthrough_feature":["When any site owner add this service to his website he need to go to every part of the page. By clicking on any part, walkthrough will be open. It will tell to add the message and also tell us how to go to the next part i.e., either by mouse click."],
    "helpeditor_feature":["The help editor will contain tooltip which is like a small hover box which will guide the users according to their requirements. There is also a richtextbox in the help editor where user can write their requirements. In these editor the different type of the help will be provided  in different pages. The users who subscribe our service will be able to edit the module according to their requirements."],
    "subscription_edit":["If You want to Edit your subscription modules then you have to go your profile page and click on manage modules and after that you edit or disable you modle package from your services."],
    "card_detect":["Our credit card processing vendor enables us to accept both MasterCard and Visa credit and debit cards."],
    "affirm_up":["Yes! you can. Just go your profile page and Click on edit service plan and do your change according your need."],
    "affirm_trial":["yes! we provide free trial of 30 days for new customer."],
    "wallet":["Yes! We are accepting Payment through wallets. We currently use only Paytm, Mobikwik, Freecharge, Ola Money, Jio Money "],
    "offers":["Sorry! We are not providing any offers for you."],
    "cancel":["Just go through you profile page and click on Edit option and select module which you want cancel it."],
    "affirm_cancel":["Yes!! You can cancel subscription whenever you want."],
    "changes":["Yes! you can change your module after subscribing it. Just go through profile page and click on Edit after that select module which you want to modify."],
    "payment_terms":["We invoice on monthly basis and payment is due on invoicing."],
    "affirm_expire":["After you free trial expire you are not authorise more to used our service and you are not been able to extend it. If you want to use our service more you have to purchase it."],
    "subscription_expire":["When your subscription ends, the records you purchased are still owned by you. In the purchase order, you agreed to delete D&B licensed material; however, We does not delete anything after the service is terminated."],
    "afternoon":["Hey!! Good Afternoon"],
    "limit":["you can add as many as module according to your subscription"],
    
    
}

